name: Check Links
on: [workflow_dispatch, push]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    
    - name: check for broken links
      run: |
        pip install fastlinkcheck
        link_check public
        
    - name: check for broken links
          run: |
           pip install fastlinkcheck
           link_check "docs/_site" --host "docs.fast.ai" 2> err || true
            export GITHUB_TOKEN="YOUR_TOKEN"
            if [[ -z $(gh issue list -l "broken-link")) && (-s err) ]]; then
              gh issue create -t "Broken links found" -b "$(< err)" -l "broken-link" -R "yourusername/yourrepo"
            fi
